### ISSUE TITLE
Hello, I'm here again.

### ISSUE THREAD

**Issue by Judy01311110** [penguin0616/Insight#1]
I used the 11/18 update and this warning appeared ↓↓↓ 
<img width="716" alt="1" src="https://user-images.githubusercontent.com/74226129/99507332-35ea3a80-29be-11eb-8725-44d3df81f468.PNG">

I'm going to trouble you again! Thank you so much.
(Google Translate)

[client_log.txt](https://github.com/penguin0616/Insight/files/5558926/client_log.txt)
[server_log.txt](https://github.com/penguin0616/Insight/files/5558927/server_log.txt)
or
[server_log.txt](https://github.com/penguin0616/Insight/files/5558952/server_log.txt)

**Comment by penguin0616** [comment]
@Judy01311110 What language is your DST using?
Do you have any language mods?

**Comment by Judy01311110** [comment]
Yes, Chinese.

**Comment by penguin0616** [comment]
Can you provide a picture of your language selection screen from the settings?

**Comment by Judy01311110** [comment]
The main picture：
<img width="848" alt="2" src="https://user-images.githubusercontent.com/74226129/99605025-ca49b100-2a41-11eb-8373-fb7e9140e027.PNG">
My options：
<img width="657" alt="3" src="https://user-images.githubusercontent.com/74226129/99605035-cf0e6500-2a41-11eb-83e5-a5d655c39472.PNG">
Other options：
<img width="645" alt="4" src="https://user-images.githubusercontent.com/74226129/99605071-e9e0d980-2a41-11eb-8710-c2085822442a.PNG">
<img width="639" alt="5" src="https://user-images.githubusercontent.com/74226129/99605076-ebaa9d00-2a41-11eb-8cc4-a45914783ea8.PNG">
<img width="633" alt="6" src="https://user-images.githubusercontent.com/74226129/99605082-ed746080-2a41-11eb-9bdb-03ffd503f685.PNG">

This MOD URL：
https://steamcommunity.com/sharedfiles/filedetails/?id=367546858

**Comment by Judy01311110** [comment]
Bad news, I tried to turn off this MOD and use the official (Steam), but there was still a problem.

<img width="960" alt="1" src="https://user-images.githubusercontent.com/74226129/99607701-4692c300-2a47-11eb-861a-7cd993aa2641.png">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/74226129/99607705-48f51d00-2a47-11eb-91f6-950bdeab57fe.png">
<img width="851" alt="3" src="https://user-images.githubusercontent.com/74226129/99607708-4abee080-2a47-11eb-9708-ecb2a88acd4b.PNG">
<img width="960" alt="4" src="https://user-images.githubusercontent.com/74226129/99607713-4bf00d80-2a47-11eb-8557-0ade9560e67c.png">

**Comment by penguin0616** [comment]
@Judy01311110 Okay, I think I fixed it in the latest update (2.7.2). Tell me if it works, or does not work.

**Comment by Judy01311110** [comment]
I tried it and it worked very well.
Thank you very much for your help!
