### ISSUE TITLE
crashed when load the walruses

### ISSUE THREAD

**Issue by IceCapriccio** [penguin0616/insight#1]
[insight_mod_log.txt](https://github.com/penguin0616/insight/files/4605733/insight_mod_log.txt)
[log.txt](https://github.com/penguin0616/insight/files/4605737/log.txt)
OS: Windows
game version: latest version
world type: ROG
description: I run to walrus camp when fist winter comes. After about 1s when four creatures(2 walrus, 2 dogs)  appeared on the screen, game crashed.

**Comment by penguin0616** [comment]
Investigating.

**Comment by penguin0616** [comment]
Fixed!

**Comment by IceCapriccio** [comment]
Thank you!
