### ISSUE TITLE
Bug Reporting

### ISSUE THREAD

**Issue by Vodka1003** [penguin0616/insight#10]
OS: Windows 10 Pro
Game version: v422596
Host: Yes
Cave: Yes
[log](https://www.writeurl.com/text/72dqrntdjsih2hborezp/jh9ealpytxeet23rtdko)
Describe:
When bundlewrap or bundle is read, it will crash with [1916988643](https://steamcommunity.com/sharedfiles/filedetails/?id=1916988643).
Another crash occurred after entering the game, it seems to be related to [1085586145](https://steamcommunity.com/sharedfiles/filedetails/?id=1085586145).

**Comment by penguin0616** [comment]
If caves are present, I also need the server log.

**Comment by penguin0616** [comment]
I am able to use bundling wraps fine with the first mod you linked. 
![image](https://user-images.githubusercontent.com/23770056/89818658-c5569680-db0f-11ea-935b-b1c39d8c59c0.png)

**Comment by penguin0616** [comment]
I also do not crash with the second mod when I join.

**Comment by Vodka1003** [comment]
[client_log](https://www.writeurl.com/text/ipsam0xdncct6ibhib43/x3jkvvppk7otp7wga0j2)
[server_log_Master](https://www.writeurl.com/text/bd1d304pum0kwo5e9o68/ehj8o1bzk0dx2k1wueh6)
[server_log_Caves](https://www.writeurl.com/text/6va615l0skc4wht430io/heumaz2x1lti8cjee76a)
I have checked every mods one by one and narrow down to [this](https://steamcommunity.com/sharedfiles/filedetails/?id=2194198291).
But the problems still exist.

So I  checked the Client Mod instead, discovered that the problems seems to be related to my translation mod (Traditional Chinese).

I have tested 
[1111711682](https://steamcommunity.com/sharedfiles/filedetails/?id=1111711682)
[367546858](https://steamcommunity.com/sharedfiles/filedetails/?id=367546858&searchtext=%E4%B8%AD%E6%96%87)
[1993780385](https://steamcommunity.com/sharedfiles/filedetails/?id=1993780385&searchtext=%E4%B8%AD%E6%96%87)
[1418746242](https://steamcommunity.com/sharedfiles/filedetails/?id=1418746242&searchtext=%E4%B8%AD%E6%96%87)
running any of them independently will cause these situations.

Note:
I deactivated every server mods except Show Me+, it still crashed with the translation mod

**Comment by penguin0616** [comment]
Can I have a link to the translation mod? It might have the same problem that Chinese++ does.

**Comment by Vodka1003** [comment]
Yes, thank you
1. [1111711682 正體中文語言包 Traditional Chinese Language Pack](https://steamcommunity.com/sharedfiles/filedetails/?id=1111711682)
2. [367546858 中文語言包](https://steamcommunity.com/sharedfiles/filedetails/?id=367546858&searchtext=%E4%B8%AD%E6%96%87)
3. [1993780385 正體中文包](https://steamcommunity.com/sharedfiles/filedetails/?id=1993780385&searchtext=%E4%B8%AD%E6%96%87)

Re: Would you like the mod to disable the text popup if that mod is enabled?
If that doesn't bother you...then sure, thank you very much!

**Comment by penguin0616** [comment]
1. Causes a crash. Looking at the code reveals it has the same problem as Chinese++, where they modify a function they should not be modifying.
2. Works fine
3. Works fine

**Comment by penguin0616** [comment]
Fixed in 56b12b452d5fdbbc39732065c8294b2a7ceb2670
Insight now hides its information for bundling wraps if that one mod is enabled.
