### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by neji0924** [penguin0616/Insight#11]
/scripts/components/insight_replica.lua:829  attempt to concatenate field 'prefab' (a nil value)

![crash](https://user-images.githubusercontent.com/25678334/122626268-265ddc00-d0dc-11eb-8529-665d39c2d4bc.jpg)

Thanks!

**Comment by penguin0616** [comment]
1. Try turning off "Item Info". 
2. I need a full log to be able to determine the cause.

**Comment by neji0924** [comment]
[log.txt](https://github.com/penguin0616/Insight/files/6679957/log.txt)

i have turned off "item info" 

Thank you

**Comment by neji0924** [comment]
I turned off "純淨輔助", it suddenly worked! So ignore this issue thanks
