### ISSUE TITLE
Thermal stone durability shows always at 100%

### ISSUE THREAD

**Issue by jkramr** [penguin0616/insight#11]
Thermal stone durability shows always at 100% in inventory icon:
![image](https://user-images.githubusercontent.com/1822434/89815108-e4bfe480-db4c-11ea-9cbf-a851ed5afd55.png)
All stones show 100% no matter how much actual durability left. Switched back to ShowMe, and it showed correctly for me.
As you can see the issue is only with the inventory icon, but shows correctly in the description.

**Comment by penguin0616** [comment]
Unable to reproduce.

**Comment by jkramr** [comment]
https://www.youtube.com/watch?v=GXK8rtvrcJM
Repro with all mods disabled but Insight

**Comment by jkramr** [comment]
debug server log
![image](https://user-images.githubusercontent.com/1822434/89837104-ee5b4380-db70-11ea-9563-0b6c2a14fada.png)
[server_log.txt](https://github.com/penguin0616/insight/files/5053700/server_log.txt)
https://youtu.be/H1v5wsMZ-6U

**Comment by jkramr** [comment]
[modmain.lua.txt](https://github.com/penguin0616/insight/files/5053792/modmain.lua.txt)

**Comment by jkramr** [comment]
[client_log.txt](https://github.com/penguin0616/insight/files/5053803/client_log.txt)
updated client log  after replacing modmain

**Comment by jkramr** [comment]
DEBUG mod with latest github and DEBUG_ENABLED=true
[client_log.txt](https://github.com/penguin0616/insight/files/5054033/client_log.txt)

**Comment by jkramr** [comment]
Original mod with latest github (except modinfo) and DEBUG_ENABLED=true
[client_log.txt](https://github.com/penguin0616/insight/files/5054073/client_log.txt)

**Comment by penguin0616** [comment]
Fixed.
