### ISSUE TITLE
Hovering over Souls (Wortox) prevents other edible items from showing correct info

### ISSUE THREAD

**Issue by Erid** [penguin0616/insight#12]
While playing with Wortox I was happy to see the hunger values matched properly and that the soul values were there; however, I noticed that after hovering on the souls the other items values would show the same as the Soul (only for Hunger, Sanity and Health).

Before hovering over a soul:
![image](https://user-images.githubusercontent.com/703220/90002845-76fce100-dc50-11ea-9da7-76e0bb923b44.png)

Hovering over a soul:
![image](https://user-images.githubusercontent.com/703220/90002873-8419d000-dc50-11ea-9d29-f68a5388d838.png)

After hovering over a soul:
![image](https://user-images.githubusercontent.com/703220/90002901-8d0aa180-dc50-11ea-91cd-794f4d3c244a.png)

Server log:
https://www.writeurl.com/publish/b58gwc817khuzu9aorqh

Please let me know if you're able to reproduce or if you need more info. I appreciate your work on this plugin, it's amazing :)

**Comment by penguin0616** [comment]
Fixed in 56b12b452d5fdbbc39732065c8294b2a7ceb2670

**Comment by penguin0616** [comment]
Thanks for your report!
