### ISSUE TITLE
Show Me+ crashed with Deluxe Cooking Pot

### ISSUE THREAD

**Issue by Vodka1003** [penguin0616/Insight#13]
- OS: Windows 10 Pro
- Game version: v422596
- Host: Yes
- Cave: Yes
- [client_log](https://www.writeurl.com/text/7srgn9e4yniuig66txzb/28ukb26jrastcxr2xprr/yz1x1qv7zj0z2b7ptz8m)
[server_log_master](https://www.writeurl.com/text/gffdro91cbsn4jmmlm62/7wug8rd63jp30dsc2jvw/09zhmycl2qarnv22m90u)

- Describe:
Using [907007729](https://steamcommunity.com/sharedfiles/filedetails/?id=907007729)'s [Deluxe Cooking Pot](https://steamcommunity.com/sharedfiles/filedetails/?id=907007729) would cause the game crashed.

**Comment by penguin0616** [comment]
Looks like they were replacing the stewer component in the prefab.
Fixed by 61f0b547c2c7e137b92bbca5cc1abd8aa609b307
