### ISSUE TITLE
Show Me+ crashed with Myth Words theme

### ISSUE THREAD

**Issue by Vodka1003** [penguin0616/Insight#14]
- OS: Windows 10 Pro
- Game version: v426792
- Host: Yes
- Cave: Yes
- [server_log](https://www.writeurl.com/text/7yan7oinbmn4l84a713h/0gfu8o9xkha6jsad69oy)
- Describe:
When Show Me+ and Myth Words theme work together, they crashed when checking Suspicious Dirt Piles

**Comment by penguin0616** [comment]
Fixed by cb5da4130744c2036db8157b25441f1f691afaab
