### ISSUE TITLE
Show Me+ crash

### ISSUE THREAD

**Issue by Vodka1003** [penguin0616/Insight#15]
- [client_log](https://www.writeurl.com/text/4jy6jwoojc47ka5bthpl/as3mvbu16k9xs8y02p22)
- [server_log](https://www.writeurl.com/text/xvdk4e8gs4caysq9rnmm/eyogymsyqicgon988c2h)
- OS: Windows 10 Pro
- Game version: v427361
- Host: Yes
- Cave: Yes
- Describe:
Game crashed when investigating Suspicious Dirt Piles, it only happens when I'm playing with my friend.

**Comment by penguin0616** [comment]
Has a fix coming in the next update.

**Comment by penguin0616** [comment]
Should be fixed now!
