### ISSUE TITLE
Rainometer crash

### ISSUE THREAD

**Issue by Vodka1003** [penguin0616/Insight#16]
- [client_log](http://download1478.mediafire.com/q1357a9b14jg/45trbmsn46b5m3e/client_log.txt)
- [server_log](http://download1512.mediafire.com/egkwe6gv5bhg/xyucygnd85ztfw4/server_log_Master.txt)
- OS: Windows 10 Pro
- Game version: v428872
- Host: Yes
- Cave: Yes
- Describe:
When pointing at Rainometer, it causes the game to crash.
This situation only happens in a save file, I can't reproduce this bug in other worlds. I'm not sure if this was affected by other mods.

**Comment by penguin0616** [comment]
Fixed in cb3186a1c383eaa1db3630ef9e64d8da178e2bfa
