### ISSUE TITLE
Server crash - version 2.1.4 (latest)

### ISSUE THREAD

**Issue by Zathrox** [penguin0616/Insight#17]
Hello Penguin, 

Had a crash with your mod tonight, happened twice in a row, both in the same situation.

**Context before crash:**
Was trying to socket purple gems into Telelocator Focus which was near a winona catapult/gemarator for a varg farm.

**Log:**
[string "../mods/workshop-2189004162/scripts/time.lu..."]:99: bad argument #2 to 'format' (string expected, got nil)
LUA ERROR stack traceback:
=[C]:-1 in (field) format (C) <-1--1>
../mods/workshop-2189004162/scripts/time.lua:99 in () ? (Lua) <92-112>
   self =
      base_seconds = -1.#IND
      context = table: 1D04A570
   short = true
   days = nil
   segments = nil
   str = nil
=(tail call):-1 in ()  (tail) <-1--1>
../mods/workshop-2189004162/scripts/descriptors/fueled.lua:21 in (local) descriptor (Lua) <2-51>
   self =
      sections = 6
      sectionfn = function - scripts/prefabs/winona_battery_high.lua:335
      rate = 0
      rate_modifiers = table: 1F08E1F0
      inst = 102070 - winona_battery_high (valid:true)
      bonusmult = 1
      period = 1
      consuming = false
      _ = table: 1F09DD58
      depleted = function - scripts/prefabs/winona_battery_high.lua:318
   context = table: 1D04A570
   inst = 102070 - winona_battery_high (valid:true)
   description = nil
   fuel_verbosity = 2
   remaining_time = *** failed to evaluate ***
   efficiency = 1
   timeString = nil
   typ = Durability
../mods/workshop-2189004162/modmain.lua:642 in (global) GetItemInformation (Lua) <590-734>
   item = 102070 - winona_battery_high (valid:true)
   player = 125712 - wolfgang (valid:true)
   params = table: 04BA8308
   player_context = table: 1D04A570
   isForge = false
   components = table: 1F09D498
   chunks = table: 04BA8150
   name = fueled
   component = table: 1F09DBC8
   descriptor = function - ../mods/workshop-2189004162/scripts/descriptors/fueled.lua:2
../mods/workshop-2189004162/modmain.lua:778 in (global) RequestItemInformation (Lua) <737-804>
   item = 102070 - winona_battery_high (valid:true)
   player = 125712 - wolfgang (valid:true)
   params = table: 04BA8308
   id = 139181
../mods/workshop-2189004162/modmain.lua:1399 in () ? (Lua) <1396-1400>
   player = 125712 - wolfgang (valid:true)
   entity = 102070 - winona_battery_high (valid:true)
   params = table: 04BA8308
=[C]:-1 in (method) CallRPC (C) <-1--1>
scripts/networkclientrpc.lua:950 in (global) HandleRPCQueue (Lua) <941-958>
   i = 1
   fn = function - ../mods/workshop-2189004162/modmain.lua:1396
   sender = 125712 - wolfgang (valid:true)
   data = table: 1EFCABE0
   tick = true
scripts/update.lua:41 in () ? (Lua) <33-129>
   dt = 0.016667099669576

[00:09:51]: [string "../mods/workshop-2189004162/scripts/time.lu..."]:99: bad argument #2 to 'format' (string expected, got nil)
LUA ERROR stack traceback:
    =[C]:-1 in (field) format (C) <-1--1>
    ../mods/workshop-2189004162/scripts/time.lua:99 in () ? (Lua) <92-112>
    =(tail call):-1 in ()  (tail) <-1--1>
    ../mods/workshop-2189004162/scripts/descriptors/fueled.lua:21 in (local) descriptor (Lua) <2-51>
    ../mods/workshop-2189004162/modmain.lua:642 in (global) GetItemInformation (Lua) <590-734>
    ../mods/workshop-2189004162/modmain.lua:778 in (global) RequestItemInformation (Lua) <737-804>
    ../mods/workshop-2189004162/modmain.lua:1399 in () ? (Lua) <1396-1400>
    =[C]:-1 in (method) CallRPC (C) <-1--1>
    scripts/networkclientrpc.lua:950 in (global) HandleRPCQueue (Lua) <941-958>
    scripts/update.lua:41 in () ? (Lua) <33-129>
	
[00:09:51]: Warning: Widget:SetFocusFromChild is happening on a widget outside of the screen/widget hierachy. This will cause focus moves to fail. Is 	ScriptErrorWidget	not a screen?	
[00:09:51]: stack traceback:
	scripts/widgets/widget.lua:605 in (method) SetFocusFromChild (Lua) <602-627>
	scripts/widgets/widget.lua:624 in (method) SetFocusFromChild (Lua) <602-627>
	scripts/widgets/widget.lua:624 in (method) SetFocusFromChild (Lua) <602-627>
	scripts/widgets/widget.lua:656 in (method) SetFocus (Lua) <629-665>
	scripts/widgets/menu.lua:83 in (method) SetFocus (Lua) <74-85>
	scripts/widgets/scripterrorwidget.lua:109 in (method) OnUpdate (Lua) <102-119>
	scripts/update.lua:90 in () ? (Lua) <33-129>

**Comment by Zathrox** [comment]
Updated on the context, simply hovering over the winona gemerator crashes the server. Did some testing on what was the actual cause.

**Comment by penguin0616** [comment]
Fixed in 8f2b9432981f2b7333cd736976b1be442bdc82f5
