### ISSUE TITLE
Not compatible with modded spices (Crash)

### ISSUE THREAD

**Issue by Legend-Master** [penguin0616/insight#18]
> https://github.com/penguin0616/Insight/blob/d977be7f1fbd25ffe01c3334dd2a57d64e69dbeb/scripts/helpers/debuff.lua#L250
> ```lua
> for prefab, data in pairs(spicedfoods) do
> 	if data.spice ~= "SPICE_SALT" then
> 		local spice_buff = SPICES[data.spice].prefabs[1]
> 		debuff_effects[prefab] = {
> 			[spice_buff] = {
> 				prefab = spice_buff,
> 				data = SPICES_STATS[data.spice]
> 			}
> 		}
> 
> 		local original = debuff_effects[data.basename]
> 		if original then
> 			for buffname, buffdata in pairs(original) do
> 				debuff_effects[prefab][buffname] = buffdata
> 			end
> 		end
> 	end
> end
> ```

Crashed on `local spice_buff = SPICES[data.spice].prefabs[1]`, log: `attempt to index field 'prefabs' (a nil value)` (Well, it actually crashed on `scripts/descriptors/eater.lua:47`, log: `attempt to call field 'GetFoodStatsForEntity' (a nil value)`, but the deepest reason is this)

May change hard coded `data.spice ~= "SPICE_SALT"` to somthing like `data.prefabs ~= nil`?

And here's my code about adding a new spice: [spices.lua](https://github.com/AkinoYuiko/DST-NightStories/blob/ea63317d5a1a524e98619e9e3d92e6f02b1fa556/main/spices.lua)

**Comment by penguin0616** [comment]
Fixed in 100477b10cbc00469d3efb931b074d1b64c914b4.
