### ISSUE TITLE
2.1.8 Crash - hovering over Abigail's flower while ink-splatted

### ISSUE THREAD

**Issue by myxal** [penguin0616/Insight#19]
Get ink-splatted by a squid, then point at Abigail's flower while your vision is blocked (I'm on a boat, Abigail is already summoned):

> [00:48:28]: vel:        0.94742929665842        
> [00:48:33]: Invalid RPC data type
> [00:48:33]: Invalid RPC data type
> [00:49:16]: vel:        0.55321867413546        
> [00:49:16]: FLOTSAM PREFAB      driftwood_log   
> [00:49:37]: ink 
> [00:49:38]: [string "../mods/workshop-2189004162/scripts/descrip..."]:83: attempt to index field 'timer' (a nil value)
> LUA ERROR stack traceback:
> ../mods/workshop-2189004162/scripts/descriptors/debuffable.lua:83 in (local) descriptor (Lua) <68-117>
>    self =
>       debuffs = table: 0x600048a24b00
>       inst = 125088 - wendy (valid:true)
>       followoffset = (0.00, -200.00, 0.00)
>       followsymbol = headbase
>       _ = table: 0x600048a24a00
>    context = table: 0x60004b04f940
>    inst = 125088 - wendy (valid:true)
>    description = nil
>    list = table: 0x6000087e1680
>    debuffPrefab = squid_ink_player_fx
>    v = table: 0x6000088c8900
>    debuff = 245648 - squid_ink_player_fx (valid:true)
>    definition = table: 0x6000087e2f40
>    remaining_time = ?
>    icon = nil
> ../mods/workshop-2189004162/modmain.lua:640 in (global) GetItemInformation (Lua) <588-732>
>    item = 125088 - wendy (valid:true)
>    player = 125088 - wendy (valid:true)
>    params = table: 0x6000087e5180
>    player_context = table: 0x60004b04f940
>    isForge = false
>    components = table: 0x6000489e7780
>    chunks = table: 0x6000087e4800
>    name = debuffable
>    component = table: 0x600048a249c0
>    descriptor = function - ../mods/workshop-2189004162/scripts/descriptors/debuffable.lua:68
> ../mods/workshop-2189004162/modmain.lua:776 in (global) RequestItemInformation (Lua) <735-802>
>    item = 125088 - wendy (valid:true)
>    player = 125088 - wendy (valid:true)
>    params = table: 0x6000087e5180
>    id = 125088
> ../mods/workshop-2189004162/modmain.lua:1398 in () ? (Lua) <1395-1399>
>    player = 125088 - wendy (valid:true)
>    entity = 125088 - wendy (valid:true)
>    params = table: 0x6000087e5180
> =[C]:-1 in (method) CallRPC (C) <-1--1>
> scripts/networkclientrpc.lua:950 in (global) HandleRPCQueue (Lua) <941-958>
>    i = 1
>    fn = function - ../mods/workshop-2189004162/modmain.lua:1395
>    sender = 125088 - wendy (valid:true)
>    data = table: 0x600008a11a80
>    tick = true
> scripts/update.lua:41 in () ? (Lua) <33-129>
>    dt = 0.018640087917447
> 
> [00:49:38]: [string "../mods/workshop-2189004162/scripts/descrip..."]:83: attempt to index field 'timer' (a nil value)
> LUA ERROR stack traceback:
>     ../mods/workshop-2189004162/scripts/descriptors/debuffable.lua:83 in (local) descriptor (Lua) <68-117>
>     ../mods/workshop-2189004162/modmain.lua:640 in (global) GetItemInformation (Lua) <588-732>
>     ../mods/workshop-2189004162/modmain.lua:776 in (global) RequestItemInformation (Lua) <735-802>
>     ../mods/workshop-2189004162/modmain.lua:1398 in () ? (Lua) <1395-1399>
>     =[C]:-1 in (method) CallRPC (C) <-1--1>
>     scripts/networkclientrpc.lua:950 in (global) HandleRPCQueue (Lua) <941-958>
>     scripts/update.lua:41 in () ? (Lua) <33-129>
>         
> [00:49:38]: Warning: Widget:SetFocusFromChild is happening on a widget outside of the screen/widget hierachy. This will cause focus moves to fail. Is   ScriptErrorWidget       not a screen?   
> [00:49:38]: stack traceback:
>         scripts/widgets/widget.lua:605 in (method) SetFocusFromChild (Lua) <602-627>
>         scripts/widgets/widget.lua:656 in (method) SetFocus (Lua) <629-665>
>         scripts/widgets/scripterrorwidget.lua:107 in (method) OnUpdate (Lua) <102-119>
>         scripts/update.lua:90 in () ? (Lua) <33-129>    
> [00:49:42]: Warning: Widget:SetFocusFromChild is happening on a widget outside of the screen/widget hierachy. This will cause focus moves to fail. Is   ScriptErrorWidget       not a screen?   
> [00:49:42]: stack traceback:
>         scripts/widgets/widget.lua:605 in (method) SetFocusFromChild (Lua) <602-627>
>         scripts/widgets/widget.lua:624 in (method) SetFocusFromChild (Lua) <602-627>
>         scripts/widgets/widget.lua:624 in (method) SetFocusFromChild (Lua) <602-627>
>         scripts/widgets/widget.lua:656 in (method) SetFocus (Lua) <629-665>
>         scripts/widgets/menu.lua:83 in (method) SetFocus (Lua) <74-85>
>         scripts/widgets/scripterrorwidget.lua:109 in (method) OnUpdate (Lua) <102-119>
>         scripts/update.lua:90 in () ? (Lua) <33-129>    
> [00:49:42]: Warning: Widget:SetFocusFromChild is happening on a widget outside of the screen/widget hierachy. This will cause focus moves to fail. Is   ScriptErrorWidget       not a screen?   
> [00:49:42]: stack traceback:
>         scripts/widgets/widget.lua:605 in (method) SetFocusFromChild (Lua) <602-627>
>         scripts/widgets/widget.lua:656 in (method) SetFocus (Lua) <629-665>
>         scripts/widgets/scripterrorwidget.lua:107 in (method) OnUpdate (Lua) <102-119>
>         scripts/update.lua:90 in () ? (Lua) <33-129>    
> [00:49:43]: Warning: Widget:SetFocusFromChild is happening on a widget outside of the screen/widget hierachy. This will cause focus moves to fail. Is   ScriptErrorWidget       not a screen?   
> [00:49:43]: stack traceback:
>         scripts/widgets/widget.lua:605 in (method) SetFocusFromChild (Lua) <602-627>
>         scripts/widgets/widget.lua:624 in (method) SetFocusFromChild (Lua) <602-627>
>         scripts/widgets/widget.lua:624 in (method) SetFocusFromChild (Lua) <602-627>
>         scripts/widgets/widget.lua:624 in (method) SetFocusFromChild (Lua) <602-627>
>         scripts/widgets/widget.lua:656 in (method) SetFocus (Lua) <629-665>
>         scripts/widgets/scripterrorwidget.lua:107 in (method) OnUpdate (Lua) <102-119>
>         scripts/update.lua:90 in () ? (Lua) <33-129>    
> [00:49:44]: Force aborting...

**Comment by penguin0616** [comment]
Fixed by 9b19e427088507d13587a89968d6eb89801790e7
