### ISSUE TITLE
Bug: crashes when interacting with Mod Wharang

### ISSUE THREAD

**Issue by cry2011cry** [penguin0616/insight#19]
Hi, I met a server crash when I played on my host server. I think it is caused due to interaction with mod https://steamcommunity.com/sharedfiles/filedetails/?id=2597089013.

The crash happened when I put foods(such as meat or seeds) into the backpack space provided by Wharang mod backpack 狐狸月盘.

Attached is the server log and client log. I only found errors reported in the master server log
[cave_server_log.txt](https://github.com/penguin0616/Insight/files/7845042/cave_server_log.txt)
[client_log.txt](https://github.com/penguin0616/Insight/files/7845043/client_log.txt)
[master_server_log.txt](https://github.com/penguin0616/Insight/files/7845044/master_server_log.txt)
.

**Comment by penguin0616** [comment]
The cause is a programming error with the mod you have linked to. They need to fix their food preservation code.
