### ISSUE TITLE
Game Crash on startup

### ISSUE THREAD

**Issue by ABirdNamedSuki** [penguin0616/Insight#2]
Reported by Steam user Nish the Fish.

Game crashes (the mod by itself) with or without DLCs installed the moment the world and character appear.
Occasionally, game will not crash, but Maxwell will appear and not interact with the player. Game is soft locked.
Crash Log Below:
[log.txt](https://github.com/penguin0616/Insight/files/5691026/log.txt)

Game run on Windows 10, Don't Starve Standalone, Any/no dlcs installed.
No other settings are tweaked before crash.

Interesting note, the second mod log by insight that is supposed to be found in the dont starve "data" folder is not present after multiple resets.
Maybe a longshot, but this is possibly because my dont starve folder is not in my (c) drive. I have it in my f drive. 
Could be an unrelated issue.

**Comment by penguin0616** [comment]
Does the latest update (2.8.5) fix it for you?

**Comment by ABirdNamedSuki** [comment]
Initial Impressions are very strong. World runs in the beginning without issue for no DLC's (mod still by itself).
Also, did not know you could look up the wiki page for items with the blueprint button. SO cool.
Will report back later on other DLC's/other mods loaded.

**Comment by ABirdNamedSuki** [comment]
I am still not seeing your mod's log report. 
You did say to look in the data folder, right?
![Don'tStarveDataFolder](https://user-images.githubusercontent.com/61896597/102151316-95fac200-3e40-11eb-955e-7a483c3ec3c5.PNG)

Unless that Debug Log is from you?

I am going to attach it anyway.
[debug.log](https://github.com/penguin0616/Insight/files/5692327/debug.log)

You were very specific about the name of the file on the steam page "insight_mod_log.txt"

**Comment by penguin0616** [comment]
That file hasn't been used in quite some time, I forgot to take it out of the instructions. Don't worry about it.
I'll go ahead and close the issue, let me know if other issues arise.
Thanks for your report.

Fixed by 406329d1c7e20444ee0d27799f1e87fc93050eb8
