### ISSUE TITLE
Improved farm hover crash

### ISSUE THREAD

**Issue by RetAlex** [penguin0616/insight#2]
## Prerequisites
Game was created as RoG, **no** compatibility with other addons selected.
No other mods enabled
Mod settings are defaulted

## Ways to reproduce
Download game save from attachments. Create a backup of currently available saves from `C:\Program Files (x86)\Steam\userdata\<USER_ID>\219740\remote`. Disable steam cloud sync. Delete everything from the saves folder mentioned above. Copy files from archive to saves folder. Load the game. Load "Survival 1-11" save. Place a seed from inventory to an improved farm in the upper-left corner. Hover the farm with a seed in it.

## Available details
Crash log:
[log.txt](https://github.com/penguin0616/insight/files/4644852/log.txt)

Insight mod log:
[insight_mod_log.txt](https://github.com/penguin0616/insight/files/4644878/insight_mod_log.txt)
P.s. the log is from "load game -> plant seed -> hover mouse -> crash" sequence

Game save:
[save.zip](https://github.com/penguin0616/insight/files/4645059/save.zip)

**Comment by penguin0616** [comment]
Commit 74c7e0705678b22d4faed3866ca760fcee765f7d closes #2
