### ISSUE TITLE
Year of the Catcoon

### ISSUE THREAD

**Issue by Link-AM** [penguin0616/insight#20]
I believe this mod is conflicting with year of the catcoon update and results in a server crash.  It appears to be due to a nil value in inventory.lua.  Note I have a few other mods enabled also, listed at the bottom of my server log.

[server_log.txt](https://github.com/penguin0616/Insight/files/7975238/server_log.txt)

[00:25:02]: [workshop-2189004162 (Insight)]:	A crash has occured.	
[00:25:02]: [workshop-2189004162 (Insight)]:	Title:	WARNING!	
[00:25:02]: [workshop-2189004162 (Insight)]:	Text:	[string "scripts/components/inventory.lua"]:716: attempt to index local 'inst' (a nil value)
LUA ERROR stack traceback:
        scripts/components/inventory.lua:716 in (method) GiveItem (Lua) <715-853>
        scripts/prefabs/catcoonden.lua:101 in (method) CacheItemsAtHome (Lua) <95-104>
        scripts/prefabs/catcoon.lua:322 in (local) fn (Lua) <319-324>
        scripts/entityscript.lua:1112 in (method) PushEvent (Lua) <1099-1126>
        scripts/actions.lua:1998 in (field) fn (Lua) <1995-2015>
        scripts/bufferedaction.lua:25 in (method) Do (Lua) <21-35>
        scripts/entityscript.lua:1415 in (method) PerformBufferedAction (Lua) <1402-1425>
        scripts/stategraphs/SGcatcoon.lua:134 in () ? (Lua) <133-136>
        =(tail call):-1 in ()  (tail) <-1--1>
        scripts/stategraph.lua:406 in (method) HandleEvents (Lua) <400-420>
        scripts/stategraph.lua:154 in (method) UpdateEvents (Lua) <148-157>
        scripts/stategraph.lua:145 in (method) Update (Lua) <109-146>
        scripts/update.lua:282 in () ? (Lua) <218-292>

**Comment by penguin0616** [comment]
This is a bug with the game, not Insight.
