### ISSUE TITLE
2.1.9 - boat health flickers when moving from clickable item to boat floor

### ISSUE THREAD

**Issue by myxal** [penguin0616/Insight#20]
Moving the mouse from a clickable object (any item on the boat, including the plank) to the boat floor makes the mod show boat health for a short time. This is very distracting when there are many items on the boat, some of which have their own health.

I have refresh delay set to 0.5s, if that's important.

![Screenshot 2020-09-13 at 14 43 48](https://user-images.githubusercontent.com/16622343/93018369-92506880-f5cf-11ea-8662-512e2b3f20de.png)

https://youtu.be/k0vcCVHeA4A

**Comment by penguin0616** [comment]
@myxal This isn't really something I can do anything about. It's all based on the client's performance and thus the time it takes for DST to hide/show its text.
