### ISSUE TITLE
mod 冲突

### ISSUE THREAD

**Issue by winds365** [penguin0616/insight#21]
https://steamcommunity.com/sharedfiles/filedetails/?id=2738170176
跟这个mod冲突，必须关闭食物信息显示
Conflicting with this mod, food information display must be turned off

**Comment by penguin0616** [comment]
I will need your logs.

**Comment by winds365** [comment]
> I will need your logs.

https://winds.ml/server.log

**Comment by penguin0616** [comment]
It looks like the mod in question, "Eirudy", isn't properly overriding food value functions. 
They need to make sure the eater component actually exists before attempting to perform logic with it.
This is an issue on their end, not mine.
