### ISSUE TITLE
Suspicious dirt piles crash

### ISSUE THREAD

**Issue by Vodka1003** [penguin0616/Insight#21]
- [client_log](http://download1595.mediafire.com/lm936ws9cnqg/12v2igeb9ss04fh/client_log.txt)
- [server_log](http://download1641.mediafire.com/6ywipp0pgdsg/x2exg37ops9wt01/server_log.txt)
- OS: Windows 10 Pro
- Game version: v428872
- Host: Yes
- Cave: Yes
- Describe:
When a player was investigating Suspicious Dirt Piles, every people except that player went crashed

https://i.imgur.com/qsdvkab.jpg

**Comment by penguin0616** [comment]
Going to assume you are G.WolfCat and will just do responses here.

**Comment by penguin0616** [comment]
@Vodka1003 Was the person doing the hunt the host?

**Comment by penguin0616** [comment]
*Probably* fixed in 3801474ca2e842920b1dcfffd5d6477894761f1f

**Comment by penguin0616** [comment]
By the way, I noticed that you've reported a lot of issues. I appreciate that. Thanks a bunch!
