### ISSUE TITLE
Crashed in "Tropical Experience Return of Them Complement"

### ISSUE THREAD

**Issue by Vodka1003** [penguin0616/Insight#22]
- [client_log](http://www.mediafire.com/file/ljhcycl8iz7jaf0/client_log.txt/file)
- [server_log](http://www.mediafire.com/file/3w86sbrqgajnyf3/server_log.txt/file)
- OS: Windows 10 Pro
- Game version: v432923
- Host: Yes
- Cave: Yes
- Describe:
The crash happened when hovering the mouse over mussel_stick (which is set on mussel_farm)

https://imgur.com/yMW4Yot
https://imgur.com/NCIPiuv

**Comment by penguin0616** [comment]
Fixed in bbb62e92a7013b24b1255c08d2c5ffabdc248ac9
