### ISSUE TITLE
Crash on server generation

### ISSUE THREAD

**Issue by Chanixy** [penguin0616/insight#22]
Hi,

Server crashes when generating world. This is a test with only insight mod activated.
github-master version manually downlaoded and installed (unzipped)

Seems like some issue in caves with sacred_chest ?

Attaching both server logs
[server_log.txt](https://github.com/penguin0616/Insight/files/8108546/server_log.txt)
[server_log.txt](https://github.com/penguin0616/Insight/files/8108547/server_log.txt)

Thx

**Comment by penguin0616** [comment]
Insight isn't running during world generation, so I doubt it is an Insight issue.
I additionally went ahead and tried generating a world with the same seed as you and got no issue.

Caves generation is quite buggy in general and often throws out many attempted generations.
The game tries to generate a map up to 5 times before throwing an error, so it looks like you were just unlucky since you used up all 5 attempts.
You should be able to generate worlds just fine normally.

**Comment by Chanixy** [comment]
Hello,

Thanks for your answer.

I have tried 8 world generations with only insight mod enabled, and none worked. As soon as I disabled insight, it worked first attempt.

On an existing (working) world, if i enable Insight (so, after generation), i can't start the server.

I'm on linux if it matters. I don't know if i can help in any other way, let me know, would really like to use Insight.

**Comment by penguin0616** [comment]
> I have tried 8 world generations with only insight mod enabled, and none worked. As soon as I disabled insight, it worked first attempt.  

I'm not sure why that would be the case, Insight doesn't do anything during world generation. It's not even running.

> On an existing (working) world, if i enable Insight (so, after generation), i can't start the server.  

This is something I can look at though. I'll need your logs.

> I'm on linux if it matters. I don't know if i can help in any other way, let me know, would really like to use Insight.  

I don't think it does? I don't have Linux so I can't test there, but no one else has reported an issue using Insight on Linux to me.
I'd have to imagine though that probably has something to do with it.

**Comment by Chanixy** [comment]
Hi,

So i generated a new world with no mods, then disconnected, then enabled insight, tried to resume world and it couldn't connect.
Here are the client log and server log.

I don't know if those are what you wanted, otherwise let me know.

Than you for your time !
[server_log.txt](https://github.com/penguin0616/Insight/files/8306233/server_log.txt)
[client_log.txt](https://github.com/penguin0616/Insight/files/8306236/client_log.txt)

**Comment by penguin0616** [comment]
You sent me the Caves log and client log.
I also needed the Master log.

**Comment by Chanixy** [comment]
Oops, here is the master server log from that session.
[server_log.txt](https://github.com/penguin0616/Insight/files/8309101/server_log.txt)

**Comment by penguin0616** [comment]
Try using the Steam version of the mod.

**Comment by Chanixy** [comment]
Hello,

Where do I find the version number used by the mod ? I'm using the stable release of Steam (1.0.0.74) and it's supposedly auto-updated. I looked into the beta branch and didn't see any newer version.

**Comment by penguin0616** [comment]
It's in the modinfo.lua file.
Your logs indicated that you're not using the Steam version of the mod, you're using what I assume is the GitHub version.

**Comment by Chanixy** [comment]
Correct, because the steam version fails to download in the game.

**Comment by penguin0616** [comment]
Okay, try this:
1. Download the latest version of Insight from the repository.  
2. Make sure the mod's root folder name is ``workshop-2189004162``.  

I think that should fix it.

**Comment by Chanixy** [comment]
Hello,

Works like a charm. Thank you for your time, much appreciate it.

Cheers

**Comment by WTBantoe** [comment]
> Okay, try this:
> 
> 1. Download the latest version of Insight from the repository.
> 2. Make sure the mod's root folder name is `workshop-2189004162`.
> 
> I think that should fix it.

Thanks!

Same crash today and ultimately found this. It works, but I still wondering why the folder name matters.
