### ISSUE TITLE
Very Slowly Dedicated Server

### ISSUE THREAD

**Issue by kju8** [penguin0616/Insight#23]
- [client_log](https://gist.github.com/kju8/81c4c2523713cdcc6c372e9471f397e6#file-client_log-txt)
- [server_log](https://gist.github.com/kju8/81c4c2523713cdcc6c372e9471f397e6#file-server_log-txt)
- OS: Windows 10 Home (Japanese)
- Game version: v438711
- Insight version: 2.6.3
- Host: Yes (Dedicated Server)
- Cave: Yes
- Describe:
A lot of logs on server are printed even though the debug mode is not turned on.(server_log line 66842-)
This makes the process very slow.

**Comment by penguin0616** [comment]
Those prints are not from Insight, they are from DST. However, I think your issue lies elsewhere.

**Comment by penguin0616** [comment]
Fixed in 62ff3e20fd0dc2e7e5f1f062fd857c97d14d75c7
