### ISSUE TITLE
Feature Request: Timer until King of the Merms starves

### ISSUE THREAD

**Issue by kju8** [penguin0616/Insight#24]
I play DST in Wurt.
It's hard to keep track of how long it takes for King of the Merms to die, and I felt it would be nice to be able to check.

**Comment by penguin0616** [comment]
I like that idea. Will add.

**Comment by penguin0616** [comment]
I added it (fefdd2d4936bdeec7de0830401560173fb0f5d77), but instead of a timer, I just decided to add a hunger meter. Not sure if I want to add health information too though.
