### ISSUE TITLE
作者大大SOS！

### ISSUE THREAD

**Issue by Judy01311110** [penguin0616/Insight#25]
11/11更新完後玩遊戲，卻就出現 ↓
(Play the game after the 11/11 update, but it appears ↓)
This server has crashed
[lnsight]:Crash reporter disabled[server].
<img width="335" alt="1" src="https://user-images.githubusercontent.com/74226129/98832485-d947c680-2477-11eb-9930-addf69f2a256.PNG">
在這之前都非常的順利。
(It's been very smooth before that.)

[client_log.txt](https://github.com/penguin0616/Insight/files/5525027/client_log.txt)
[server_log.txt](https://github.com/penguin0616/Insight/files/5525032/server_log.txt)

**Comment by penguin0616** [comment]
I am using Google Translate.
我正在使用谷歌翻译。

The files you have provided do not have the crash information, so I think you sent the wrong server_log.txt
您提供的文件没有崩溃信息，因此我认为您发送了错误的server_log.txt

Please enable the crash reporter and cause the crash again, or submit the correct server_log.txt
请启用崩溃报告程序并再次导致崩溃，或提交正确的server_log.txt

**Comment by Judy01311110** [comment]
Thank you for your kind! 
I found that the problem was the birth of Bearger, 
With 11/12 updates, there's no problem now! Thank you very much~
(Google Translate)

**Comment by penguin0616** [comment]
Fixed in c87c018fd89f577f7a6e6bd31086b5d45acde5f7
