### ISSUE TITLE
Jumping into Tentacle Hole crashed.

### ISSUE THREAD

**Issue by whittede** [penguin0616/insight#27]
Hey there! I've been using this mod for a long time, mostly without issue. I quite like it, so thank you for all of the work you have put into it!

Anyway, I killed a Big Tentacle and jumped into its hole. I popped out on the other side, moved my mouse slightly and the game crashed. I'm not sure if the crash was due to jumping through the tentacle hole, or if there was some item on the ground onscreen that I mouse over and it caused the crash. It happened so fast that it was hard to tell.

I've attached the `client_log` and `server_log`. Hopefully tracking down the issue is fairly easy! Thanks!

[client_log_2022-08-26.txt](https://github.com/penguin0616/Insight/files/9446230/client_log_2022-08-26.txt)
[server_log_2022-08-26.txt](https://github.com/penguin0616/Insight/files/9446231/server_log_2022-08-26.txt)

EDIT: I'm not on the beta, and yes Caves are enabled (lol obviously based on the story)

**Comment by whittede** [comment]
Adding a screenshot from the crash when it occured:
![image](https://user-images.githubusercontent.com/35239088/187255607-0228f790-9321-40e6-b1c5-79d9139fe002.png)

**Comment by penguin0616** [comment]
This is a crash from [Wormhole Icons [Fixed]](https://steamcommunity.com/sharedfiles/filedetails/?id=1295277999). It never updated to support the Moon Quay update.

**Comment by whittede** [comment]
Oh, you're right 🤦‍♀️ Looks like this is a well-known issue with that mod. My mistake, sorry for bothering here.

**Comment by penguin0616** [comment]
All good 👍
