### ISSUE TITLE
Crash inside of Terrarium Chest

### ISSUE THREAD

**Issue by koi-hime** [penguin0616/insight#28]
This mod crashed my game while inside of the Terrarium Chest. I was happening to use Healing Salves that were inside it at the time as well.

Here are the server and client logs.
Server - https://pastebin.com/NmAHmTLB
Client - https://pastebin.com/GTE8yeF4

**Comment by penguin0616** [comment]
Turn off the "Item Info" mod.

**Comment by koi-hime** [comment]
> Turn off the "Item Info" mod.

Thank you!
