### ISSUE TITLE
LICENSE is incompatible with README

### ISSUE THREAD

**Issue by rpdelaney** [penguin0616/insight#3]
In the README you said:

> If you decide to use any code from here, please give credit where it is due. However, reposting or just copying this mod for republishing is not permitted. 

The LICENSE, however, is the MIT license, which does not include any attribution requirements, neither for perfect copies nor derivatives.

You might prefer [GPLv3](https://choosealicense.com/licenses/gpl-3.0/) or [CC-BY](https://creativecommons.org/licenses/by/4.0/).

**Comment by penguin0616** [comment]
Thank you! I changed it to GPLv3. I think that might do it. 
I originally chose MIT because it was the recommended option. I frankly don't understand the licensing options all too well.
Commit 4089991f7ba6850e517befa1fa4dc9d429a45518 closes #3

**Comment by rpdelaney** [comment]
Cool. [choosealicense.com](https://choosealicense.com) can help in the future.
