### ISSUE TITLE
crashing while i hovering bacon scraps

### ISSUE THREAD

**Issue by xiabeizi** [penguin0616/Insight#3]
![1609491323(1)](https://user-images.githubusercontent.com/29277631/103436285-dfc31500-4c54-11eb-9206-ff4f90a7752a.jpg)
[client_log.txt](https://github.com/penguin0616/Insight/files/5758775/client_log.txt)

crashing,while i hovering bacon scraps
https://steamcommunity.com/sharedfiles/filedetails/?id=2189004162

**Comment by tshanli** [comment]
After updated to version 3.1.18, I encountered same problem, it can' be compatible with any Chinese fix mod. After I disabled them, this mod works well.
![image](https://user-images.githubusercontent.com/28787794/129449749-bc12a67e-e5e8-4f4e-9fef-aef5fd887e75.png)

**Comment by penguin0616** [comment]
@tshanli Which Chinese translation mod are you using in this case? Can you also provide the full log?

**Comment by tshanli** [comment]
> @tshanli Which Chinese translation mod are you using in this case? Can you also provide the full log?

Mod name: [Chinese++](https://steamcommunity.com/sharedfiles/filedetails/?id=1418746242)
Here the full log: 
[client_log_2021-08-14-15-52-48.txt](https://github.com/penguin0616/Insight/files/6987088/client_log_2021-08-14-15-52-48.txt)

**Comment by penguin0616** [comment]
@tshanli This will be fixed in the next update (3.1.20). Thank you for your report.
On additional testing, it seems that Chinese++ can corrupt your saves for worlds that do not have caves, do not use it there.
