### ISSUE TITLE
Mod is Active, but does not show the Extended Information

### ISSUE THREAD

**Issue by JSmurf11** [penguin0616/insight#35]
I was using the mod for a long time now, but suddenly showed some slight issues. First issue was that even with the config having the "Inspect Only" active, it still shows the extended info, however, after quitting the game it doesn't show anything anymore even when I am holding the 'alt' for the inspect option for the mod.

Here is my Logs:
Client Log: https://pastebin.com/EewBhSWi
DxDiag (if it is needed): https://pastebin.com/jiypeiVz

Attached is my Server Log/Cluster: 
[DxDiag.txt](https://github.com/penguin0616/Insight/files/10509592/DxDiag.txt)

**Comment by HubertZhang** [comment]
It seems when @penguin0616 were repairing the crash in v4.0.4, `v.description` is commented out in `modinfo.lua:1056`

**Comment by penguin0616** [comment]
@HubertZhang So *that's* what happened. It was driving me crazy.
I really should be more careful about coding when I'm tired.
Thanks for pointing it out! I'll try to get the fix released soon.

**Comment by penguin0616** [comment]
Okay, I pushed out a quick update that should fix the issue.

**Comment by penguin0616** [comment]
@JSmurf11 Is it fixed for you with the new update (4.0.6)?

**Comment by JSmurf11** [comment]
@penguin0616 Yes, the values are showing now. However, the option of "Inspect Only" doesnt work on my end

**Comment by penguin0616** [comment]
That's getting fixed later today.

**Comment by JSmurf11** [comment]
Ok, thanks for the fixes @penguin0616. And a huge thanks for creating and keeping this helpful mod up to date. Keep up the good work! Thanks again

**Comment by penguin0616** [comment]
This should be fixed now in version 4.0.7. Please confirm if it works for you now.
