### ISSUE TITLE
Insight's tooltip could overlap with other mods' tooltip

### ISSUE THREAD

**Issue by HubertZhang** [penguin0616/insight#36]
Recently I'm investigating the problem that the tooltip from insight can overlap with other mods' tooltip.

The mod Functional Medal, also modified `widget/hoverer` for displaying some introduction of its items, by overriding the function `hoverer.text.SetText()`. Since Insight has smaller priority `-10000`, Insight's `AddClassPostConstruct` call is later than Functional Medal's, thus the call to hoverer.text.SetText becomes:

```
{
    Insight's SetText stuffs, where the position of insightText is calculated
    call oldSetText {
        Functional Medal's SetText stuffs, here FM adds some description to text
        call oldSetText {
             Original SetText, the text is rendered
        }
    }
}
```

So I was considering if the position calculation part can happens after calling old SetText, then there should be no more overlaps...

**Comment by penguin0616** [comment]
I think there was a reason I put oldSetText last, but I need to double check why that was the case.

**Comment by penguin0616** [comment]
oldSetString is currently done last is Insight was able to calculate how much newline padding the text needed.
So, for a solution, the end result is that two SetStrings have to be done, the first being the overriden method and the second one being a "pure" version from the Text widget. 
It's a bit weird, but it seems to work though.
![dontstarve_steam_x64_2023-02-05_00-04-34](https://user-images.githubusercontent.com/23770056/216804451-fec55824-7a45-4b24-b37c-e448d28ddd28.png)

**Comment by penguin0616** [comment]
I pushed a commit (2012a5c9c35d67572349196fbb5ac739b84921c8) with the fix in it, can you give it a try and tell me if it solves your issue?

**Comment by HubertZhang** [comment]
It works! Tooltips no longer overlap with each other!

**Comment by penguin0616** [comment]
Sounds good! I just pushed out a release on Steam with the fix.
