### ISSUE TITLE
I can't open my world with this mod activated

### ISSUE THREAD

**Issue by vaugusto273** [penguin0616/insight#37]
Whenever I add this mod and try to open the world, it takes a while to open and at the end there is an error basically saying that there was an error and it was not possible to open a dedicated server
But as soon as I remove the mod the world reopens normally

**Comment by penguin0616** [comment]
I need your log files, or else I can't do anything about it.

**Comment by vaugusto273** [comment]
Where i can found the log file?

**Comment by penguin0616** [comment]
![steam_2023-01-29_13-54-31](https://user-images.githubusercontent.com/23770056/215352324-271661ff-0856-4ee1-9bc5-ff5817feea1d.png)

**Comment by vaugusto273** [comment]
I think I managed to solve it already, I uninstalled and reinstalled the DST and it started working
Thanks for the help, anything if it stops working I'll be back
