### ISSUE TITLE
Randomly crash when loading the game

### ISSUE THREAD

**Issue by kvarenzn** [penguin0616/insight#38]
First of all, thank you for making such an excellent mod!

#### basic information
+ OS: Linux (archlinux x64)
+ Game version: DST x64 (latest version) without any DLC
+ Mods enabled: Insight only (I created a new world and disabled other mods, but the problem still exists)
+ World options: single player, offline, cave disabled
+ Problematic Insight versions: from commit `591596` till now (version 4.0.9 / commit `2012a5`)
+ Logs:
    + `client_log.txt`: [client_log.txt](https://github.com/penguin0616/Insight/files/10676988/client_log.txt)
    + `cave_server_log.txt` & `master_server_log.txt`: cave server is disabled so DST only generates `client_log.txt`

#### details
I recently updated Insight from 3.4.5 to 4.0.7. When Insight is enabled, after clicking the 'Resume World' button, and before the 'Loading...' page appears, the game will crash randomly (no error report pop-up and the game window closed directly). I read the `client_log.txt` and didn't find any serious error messages in it. The log file ends with `Klump files loaded: 0`.
I searched for `Klump files loaded` in the DST source code and found that the game actually crashed when calling TheSim:RenderOneFrame() (`scripts/gamelogic.lua:142`). Its a C function, so I'm not sure what's going on inside. However, commenting out that line can temporarily fix the problem.
At first, I wasn't sure that the problem was caused by Insight, but when I disabled Insight, the problem disappeared. Then I tried the historical versions of Insight on github and found that commit `591596` should be the first version to have this problem. 
I compared the differences between `591596` and the previous commit `e50213`, and after some experimentation, I found that commenting out the `local InsightPresetScreen = ...` in `scripts/screens/insightconfigurationsscreen.lua` and the later `self.preset_button:SetOnClick` calls can also temporarily fix this issue. Of course, the price is that the `preset button` doesn't work anymore.

I know about lua (but not very well) and might be able to help a little. If you need more information, please let me know.

**Comment by penguin0616** [comment]
Thank you for your very detailed investigation and notes! It made it very easy to figure out where the issue was coming from :)

I had to setup a Linux VM to test this, and it seems that the newproxy calls in scripts/misc/config_presets.lua the issue.
Commenting out the keep line in specific should fix the issue for you temporarily.

Since it's a Klei issue, I'll report it to them and close this issue if it gets fixed.

**Comment by kvarenzn** [comment]
I apologize for my misjudgment, I didn't realize that this was really Klei's problem.
After commenting out the first line of `scripts/misc/config_presets.lua`, the game really didn't crash anymore, thank you for the temporary solution!

**Comment by penguin0616** [comment]
Thanks for the confirmation! 
I'll push out a fix for this crash.

**Comment by penguin0616** [comment]
The fix has been released on Steam. Thanks again for your help!

**Comment by kvarenzn** [comment]
Tried the latest version, it works well :)
Thank you for fixing it so quickly!
