### ISSUE TITLE
Discussion about adding mod boss information

### ISSUE THREAD

**Issue by HubertZhang** [penguin0616/insight#39]
Recently I was looking for a method to show a mod's boss respawn timer in World tab. But I cannot find an existing way to add it.

Normal boss spawner are traced when server load the world, then set its reference to `Shard_Insight`. However I cannot find a clean way to add other info in `GetWorldData` function.

What about adding a AddWorldDescriber methods which register a `Describe` function to `Shard_Insight` and `Shard_Insight` collects all description?

**Comment by HubertZhang** [comment]
Also I found such function can simplify current `GetWorldData`'s implementation that we don't need so much `GetSomeBossTimer` call

**Comment by penguin0616** [comment]
Is the boss respawn controlled by an entity (ex: dragonfly_spawner), or a component (ex: deerclopsspawner)?
If it's a component, you should be able to show it by adding a normal descriptor for the component. It won't be synced at the moment though.

I'm thinking out how this could work.

**Comment by penguin0616** [comment]
Solved in #42
