### ISSUE TITLE
Floating point math artifacts sometimes appear in in item durability / remaining uses

### ISSUE THREAD

**Issue by rpdelaney** [penguin0616/insight#4]
For example, I have a star caller's staff which has: `13.154858579 out of 20 uses remaining.`

**Comment by penguin0616** [comment]
I assumed uses would always be integers. Fixing.

**Comment by penguin0616** [comment]
Fixed!

**Comment by rpdelaney** [comment]
Since this rounds down, I now have a star caller's staff with 0 of 20 uses remaining and 1% durability

**Comment by penguin0616** [comment]
Okay, this should do you one better.

**Comment by rpdelaney** [comment]
Yes! That did it. Thank you!
