### ISSUE TITLE
Crash (almost sure that it is related to Crock Pot)

### ISSUE THREAD

**Issue by gpadilha** [penguin0616/Insight#4]
Hi @penguin0616 ,

Firstly, I would like to thank you for the mod. Great work!

I have started playing DS (no DLCs) recently and as soon as I built a Crock Pot my game started crashing whenever I have the Insight mod enabled. I disabled all other mods and the game still crashing with only the Insight mod enabled what makes me thing that the issue is on it.
Please find attached the log file. Let me know if you need any further information.

I'm a programmer myself but I have no knowledge in LUA; however; I might be able to help you with something technical if needed.

[log.txt](https://github.com/penguin0616/Insight/files/5805954/log.txt)

Thanks!

**Comment by penguin0616** [comment]
Fixed in a654d27bf108d26196649354b4bf5062679be970
