### ISSUE TITLE
Use server config

### ISSUE THREAD

**Issue by GinShio** [penguin0616/insight#43]
Hi, i configure this mod in server, but the game is played using the client
configuration. could i disable the client config?

**Comment by penguin0616** [comment]
Can you elaborate on what you mean? That's too vague for me to give a specific answer.

Server options are enforced for both clients and server, unless it's something that the client would have access to regardless or it's a display format, in which case the client's choice is used.

**Comment by GinShio** [comment]
for example, set highlight to purple in server config. then, i login the server, insight popup a window and set default configuration. set highlight to default value. (maybe i clicked something)

I want to always not use the client config.

**Comment by penguin0616** [comment]
Highlighting isn't meant to be controlled by the server.

The only valid case I've seen for the server having rights to client configuration was before the configuration menu: users who weren't subscribed to Insight had no way to configure client options, so I let the server choose them for users who weren't subscribed.
Now that there's a configuration menu, that use case was eliminated.

What is your use case for not always using the client configuration for client options?

**Comment by GinShio** [comment]
Oh yes, maybe I meant the configuration menu.

i want to only use server config, even if options are modified in configuration menu.
that is, disable the configuration menu (?)

**Comment by penguin0616** [comment]
Disabling the configuration menu is not an option nor something I intend to allow.

Why are you trying to force server configuration? It's meant to restrict types of information, not choose formatting/style options.
