### ISSUE TITLE
The game crashes when entering a world after a DS update

### ISSUE THREAD

**Issue by Slotterleet** [penguin0616/insight#48]
OS: Windows
Build: 571392
Game: Don't Starve (RoG + SW + Hamlet)
Current location: Shipwrecked
Crash log:
![20230905213615_1](https://github.com/penguin0616/Insight/assets/62336673/4a746d94-9ad8-43aa-a134-7e398e0db323)

**Comment by yli-magic** [comment]
我也报错了

**Comment by Slotterleet** [comment]
ok

**Comment by penguin0616** [comment]
This should be fixed now.
