### ISSUE TITLE
Feature req: Replace durability percentage with real values

### ISSUE THREAD

**Issue by rpdelaney** [penguin0616/insight#5]
I am trying out this mod as a potential replacement for [Detailed Tooltips](https://steamcommunity.com/sharedfiles/filedetails/?id=408066317) and I like it so far. I also appreciate your responsiveness & that it's in active development which should lead to fewer compatibility issues. One feature I'm missing from Detailed Tooltips is rendering the real-world durability metrics rather than percentages, because the percentage durability of an item has varying implications from one item to the next. For instance, a Tam o' Shanter (200 minutes) with 20% durability (40 minutes) actually has the same durability as a Beefalo Hat (80 minutes) with 50% durability (40 minutes). 

Detailed Tooltips has the option "Replace Icon %" to accomplish this. I can provide a screenshot if it would help. So if my Cutlass Supreme has 108 swings left, I see "108" rather than "72%". I find this more useful and intuitive than the default UI, so it would be nice if it could be implemented in the Insight mod.

**Comment by penguin0616** [comment]
I would love a screenshot, since I don't quite get what you mean.

**Comment by rpdelaney** [comment]
Sure, I made a couple screenshots for comparison here: https://imgur.com/a/kh8oOi5 Let me know if that helps

**Comment by penguin0616** [comment]
Okay, I'll give this a shot.

**Comment by penguin0616** [comment]
![image](https://user-images.githubusercontent.com/23770056/82611768-e0f07780-9b86-11ea-81c8-685dd33d1569.png)
How's this?

**Comment by rpdelaney** [comment]
That is perfect for my use-case. 

One thought I had is that if you want this mod to be adaptable to DST then thermal stones are a bit of a wrinkle because they have durability there. But I don't play DST much at all so I am indifferent to this.

Thank you very much for your great work on this mod.

**Comment by penguin0616** [comment]
Okay, it'll be a bit of time before I publish the change since I'm working on an additional feature.
I don't have any plans to port this to DST, since as far as I'm aware, Show Me already fulfills the needs of everyone there.
If I did port it, I figure I would just show durability over temperature. The color should suffice them already, and if not, they can just mouse over it.

**Comment by penguin0616** [comment]
Okay, update's out. The setting ("Inv Slot Info", rename pending) is disabled by default though.
Commit b8646a2512874657fe08e490994811deb09c2f8f
