### ISSUE TITLE
使用T建MOD瞬移的时候报错

### ISSUE THREAD

**Issue by Asuna1204** [penguin0616/insight#51]
[client_log.txt](https://github.com/penguin0616/Insight/files/13538054/client_log.txt)
[master_server_log.txt](https://github.com/penguin0616/Insight/files/13538055/master_server_log.txt)

**Comment by penguin0616** [comment]
This is not an Insight issue.

You have a mod that is, for some reason, categorizing lightning rods as the mutated plants, which the game doesn't handle.

**Comment by Asuna1204** [comment]
Thanks a lot
