### ISSUE TITLE
The mod always show indicator

### ISSUE THREAD

**Issue by phucho0237** [penguin0616/insight#52]
Game version: v586529
Mod version: v4.4.7 (Steam)

Image:
![image](https://github.com/penguin0616/Insight/assets/88989555/13ac03b5-bb22-4c32-b2c6-689714ef5d16)

**Comment by penguin0616** [comment]
These are Points of Interest from the game, not Insight.
I believe inspecting the object they point to clears them.

**Comment by phucho0237** [comment]
> These are Points of Interest from the game, not Insight. I believe inspecting the object they point to clears them.

Is there anyway to turn it off?
