### ISSUE TITLE
I encountered a bug when using the Insight

### ISSUE THREAD

**Issue by Yingzhihuo** [penguin0616/insight#54]
I have been experiencing an issue with the Insight mod for Don't Starve, which you authored. Specifically, I encounter an error either upon the completion of world generation or when attempting to enter a previously created world. I tried to re-download the game and mod, but nothing worked out. I have attempted to troubleshoot the issue myself, but I lack the expertise in the code to find a resolution.

I have located relevant logs as per your instructions on Steam and have shared them on Google Drive. Here is the link: https://drive.google.com/file/d/1vm0ZQnshEpn-JRECR5CbEjkNp88zQNLC/view?usp=drive_link.

Thank you for taking the time to look into this matter. If additional information is required, please feel free to let me know. Furthermore, I genuinely appreciate the Insight mod, to the extent that my enthusiasm for playing is dampened when I am unable to launch and enjoy the mod.

**Comment by penguin0616** [comment]
It seems that the logs are inaccessible. Did you make them public?

**Comment by Yingzhihuo** [comment]
Sorry, I forgot to change the access permissions.
https://drive.google.com/file/d/1vm0ZQnshEpn-JRECR5CbEjkNp88zQNLC/view?usp=sharing

**Comment by penguin0616** [comment]
Thanks!
This has been fixed in 2a2592ed42e6422c56c29169350ea9aa5e9ae20d and will be in the next update.

**Comment by penguin0616** [comment]
This fix is now live on steam.
