### ISSUE TITLE
Herd information seems broken in v4.4.8

### ISSUE THREAD

**Issue by Zathrox** [penguin0616/insight#55]
Commented on workshop but thought i'd also post here. 

Seems as of v: 4.4.8 herd information isn't displayed anymore for both volt goats or beefalo. Even with both server + client enabled.

![image](https://github.com/penguin0616/Insight/assets/27639802/19abda10-e21d-4484-a732-0b8e854e5c21)

I have also removed all mods, client and server and just booted up a world with insight and still nothing.

**Comment by penguin0616** [comment]
Everything still works fine for me. Did you try holding inspect?

**Comment by Zathrox** [comment]
Okay, so I had no idea what "inspect" was but for me, pressing and holding left alt and hovering showed the herd info. 
So we can close this down but could you maybe add in the mod description, somewhere that some information is always hidden until you inspect? It wasn't inherently obvious to me as I'd never really used the inspect key/options before! 

Thanks for checking it out!

**Comment by penguin0616** [comment]
A tip for checking if something has hidden information is if there's an asterisk next to the entity's name. If there is one, there's hidden info.
