### ISSUE TITLE
Certain indicators have infinite range

### ISSUE THREAD

**Issue by Nubidubi23** [penguin0616/insight#58]
Playing on the new Scrappy Scavengers update. I don't think is supposed to happen
![image](https://github.com/penguin0616/Insight/assets/48162191/6fe31bdb-c49d-4fb6-a9d5-9be06f927473)

[server_log.txt](https://github.com/penguin0616/Insight/files/14854002/server_log.txt)

**Comment by penguin0616** [comment]
These are Point of Interest indicators from Klei, not Insight.
