### ISSUE TITLE
Can't start the world with this mod.

### ISSUE THREAD

**Issue by Sir-Kabrok** [penguin0616/insight#62]
As the title says. I click on generate world on a local server, and get a warning, the game crashes. I have only Insight mod enabled.
Here's the part of the log that contains the error:

[00:04:02]: [string "scripts/shardsaveindex.lua"]:603: table index is nil
LUA ERROR stack traceback:
    scripts/shardsaveindex.lua:603 in (method) SetSlotEnabledServerMods (Lua) <587-619>
    scripts/widgets/redux/modstab.lua:1411 in (method) Apply (Lua) <1398-1421>
    scripts/screens/redux/servercreationscreen.lua:326 in (local) onCreate (Lua) <281-434>
    scripts/screens/redux/servercreationscreen.lua:570 in (method) Create (Lua) <280-572>
    scripts/screens/redux/servercreationscreen.lua:493 in (field) onclick (Lua) <490-494>
    scripts/widgets/imagebutton.lua:213 in (method) OnControl (Lua) <173-220>
    scripts/widgets/widget.lua:129 in (method) OnControl (Lua) <123-137>
    scripts/widgets/widget.lua:129 in (method) OnControl (Lua) <123-137>
    scripts/widgets/widget.lua:129 in (method) OnControl (Lua) <123-137>
    scripts/widgets/widget.lua:129 in (method) OnControl (Lua) <123-137>
    scripts/widgets/widget.lua:129 in (field) OnControl (Lua) <123-137>
    scripts/screens/redux/popupdialog.lua:77 in (method) OnControl (Lua) <76-80>
    scripts/frontend.lua:426 in (method) OnControl (Lua) <410-474>
    scripts/input.lua:165 in (method) OnControl (Lua) <162-169>
    scripts/input.lua:429 in () ? (Lua) <428-430>

**Comment by penguin0616** [comment]
I need the full log.

**Comment by Sir-Kabrok** [comment]
https://pastebin.com/LFsyPJfD

**Comment by penguin0616** [comment]
Looks like your crash has something to do with your configuration options not being properly set up on the world you're launching.
When you use the GitHub version, you have to set it up yourself.
I recommend using the workshop version, since the game will take care of the heavy lifting for you there.
