### ISSUE TITLE
Game Crashes When Returning to It from Another Window

### ISSUE THREAD

**Issue by kafca4806** [penguin0616/insight#70]
When I switch from another window, such as Chrome or Discord, back to the game window using Alt + Tab, the game crashes and an error message appears.

[caves_server_log.txt](https://github.com/user-attachments/files/16541919/caves_server_log.txt)
[client_log.txt](https://github.com/user-attachments/files/16541920/client_log.txt)
[master_server_log.txt](https://github.com/user-attachments/files/16541923/master_server_log.txt)

**Comment by penguin0616** [comment]
Looks like the new Korean translations had some structural errors.
This has been fixed in b8aabe30586befcb5484b0d60ce5fe28202c7409
